### ISSUE TITLE
removing shotstack watermark on generated videos

### ISSUE THREAD

**Issue by sblbl** [shotstack/shotstack-sdk-node#23]
Hello everybody, 
It's a dumb question, but I'm not figuring out the answer. I'm using the shotstack API to add the audio to some videos and the resulting videos always have the shotstack logo over them. Is it just because I have the free plan or do I need to do something else? Thanks for the help

<img width="543" alt="Screenshot 2023-11-14 alle 15 55 50" src="https://github.com/shotstack/shotstack-sdk-node/assets/24754994/b65a7e32-10c2-45ca-ba93-6c194e7473fe">

**Comment by jeffski** [comment]
Hi @sblbl,
This could be caused be caused by two reasons:
1. You are calling the Sandbox (staging) environment which always adds a watermark. The staging environment URL starts like this: https://api.shotstack.io/stage/ or https://api.shotstack.io/edit/stage (both work). It also has it's own API key. To get rid of the watermark use the v1 (production) URL and key. The v1 URL starts like this: https://api.shotstack.io/v1/ or https://api.shotstack.io/edit/v1/.
2. If you are using the v1 URL and on a free plan. The logo will display once you exceed the 20 credits limit.
